name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday (UTC)

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          bandit -r src/ -f json -o bandit-results.json

      - name: Run Safety dependency check
        run: |
          set -e
          safety check --full-report --output safety-results.json || true #Ignore failure as return code is always non-zero

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            bandit-results.json
            safety-results.json

      - name: Check for vulnerabilities and fail if found
        run: |
          # Check if either bandit or safety found vulnerabilities
          BANDIT_VULNS=$(jq '.results | length' bandit-results.json)  # Count the number of issues
          SAFETY_VULNS=$(jq 'length' safety-results.json)   # Count the number of issues

          if [[ "$BANDIT_VULNS" -gt 0 ]]; then
            echo "Bandit Security vulnerabilities found!"
            echo "Number of vulnerabilities found: $BANDIT_VULNS"
            jq '.results[] | { filename: .filename, line_number: .line_number, issue_severity: .issue_severity, issue_text: .issue_text }' bandit-results.json
            exit 1  # Fail the workflow
          fi

          if [[ "$SAFETY_VULNS" -gt 0 ]]; then
            echo "Safety Dependency vulnerabilities found!"
            echo "Number of vulnerabilities found: $SAFETY_VULNS"
            jq '.vulnerabilities[] | { package_name: .package_name, analyzed_version: .analyzed_version, advisory: .advisory, advisory_url: .advisory_url }' safety-results.json
            exit 1
          fi

          echo "No security vulnerabilities found."